/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Arrays:": {                                     "en": "arrays which need to be converted to objects: ",  "de": "Arrays die in Objekte konvertiert werden müssen (object|name|wert|unit durch ',' getrennt): ", "ru": "массивы, которые должны быть преобразованы в объекты: ", "pt": "arrays que necessitam de ser convertidos para objetos: ", "nl": "arrays die moeten worden geconverteerd naar objecten: ", "fr": "les tableaux qui doivent être convertis en objets: ", "it": "le matrici che devono essere convertiti in oggetti: ", "es": "las matrices que deben ser convertidos a objetos: ", "pl": "tablice, które muszą być przekształcone w obiekty: ", "zh-cn": "阵列需要加以转化为对象： "},
    "Cleanup:": {                                    "en": "Delete all objects which cased an error on download?", "de": "Alle Daten löschen die beim neu laden fehler gebracht haben?", "ru": "Удалить все объекты, которые обсаженных ошибка при загрузке?", "pt": "Elimine todos os objetos que sendo um erro no download?", "nl": "Verwijder alle voorwerpen die veroorzaakt een fout op downloaden?", "fr": "Supprimer tous les objets qui cartonne une erreur sur le téléchargement?", "it": "Eliminare tutti gli oggetti che rivestivano un errore nel download?", "es": "Eliminar todos los objetos que con carcasa de un error en la descarga?", "pl": "Usuń wszystkie obiekty, które obudowane błąd podczas ładowania?", "zh-cn": "删除所有对象，其中写错误，在下载？"},
    "Delete:": {                                     "en": "items names you want to remove and not show in ioBroker: ", "de": "Objekte/namen die nicht übertragen werden sollen: ", "ru": "названия предметов, которые вы хотите удалить и не показывать в ioBroker: ", "pt": "itens de nomes que você deseja remover e não mostrar em ioBroker: ", "nl": "items namen die u wilt verwijderen en niet laten zien in ioBroker: ", "fr": "les éléments les noms que vous souhaitez supprimer et de ne pas apparaître dans ioBroker: ", "it": "elementi di nomi che si desidera rimuovere e non mostra in ioBroker: ", "es": "los elementos de los nombres que desea eliminar y no se muestran en ioBroker: ", "pl": "nazwy przedmiotów, które chcesz usunąć i nie pokazywać się w ioBroker: ", "zh-cn": "项目名称你想要删除并不表明在ioBroker: "},
    "Flatten:": {                                    "en": "objects which should move to upper hirarchy: ",   "de": "Objekte/namen die in übergeordnete Hirarchie wandern sollen: ", "ru": "объекты, которые должны двигаться к верхней иерархия: ", "pt": "objetos que devem se mover para a parte superior do hirarchy: ", "nl": "objecten die te verplaatsen naar de bovenste hirarchy: ", "fr": "les objets qui doivent passer à la partie supérieure hirarchy: ", "it": "gli oggetti che devono spostarsi superiore hirarchy: ", "es": "los objetos que debe mover a la parte superior hirarchy: ", "pl": "obiekty, które powinny poruszać się do góry hierarchia: ", "zh-cn": "的对象，哪些应该移到上hirarchy: "},
    "Force init:": {                                 "en": "Delete all old object for this adapter incance?", "de": "Alle alten Objeke dieser Instanz beim Adapterstart löschen?", "ru": "Удалить старый объект для этого incance адаптер?", "pt": "Excluir todos os antigos objeto para esse adaptador de incance?", "nl": "Verwijder alle oude object voor deze adapter incance?", "fr": "Suppression de tous les anciens de l'objet de cette carte incance?", "it": "Eliminare tutte le vecchie oggetto di questa scheda incance?", "es": "Eliminar todos los viejos objeto de este adaptador incance?", "pl": "Usunąć stary obiekt dla tego incance zasilacz?",  "zh-cn": "删除所有旧的对象对这器incance?"},
    "Password:": {                                   "en": "password to connected drive service: ",           "de": "Passwort für ConnectedDrive Service: ",           "ru": "пароль к подключенному приводу: ",                "pt": "palavra-passe para a unidade ligada serviço: ",   "nl": "wachtwoord aangesloten drive \" - service: ",     "fr": "mot de passe de disque connecté à de service: ",  "it": "password collegata al servizio di auto: ",        "es": "contraseña para conectarse servicio de la unidad: ", "pl": "hasło do podłączonego napędu: ",                  "zh-cn": "密码连接驱动的服务： "},
    "Rename:": {                                     "en": "Rename items with old|new, ... pairs: ",          "de": "Objekte mittels alt|neu, ... umbenennen: ",       "ru": "Переименование предметов с Старые|новые, ... пар: ", "pt": "Mudar o nome de itens com o velho|novo, ... pares: ", "nl": "De naam van items wijzigen met oud|nieuw, ... paren: ", "fr": "Renommer des éléments avec ancien|nouveau, ... paires: ", "it": "Rinominare gli elementi con vecchio|nuovo, ... coppie: ", "es": "Cambiar el nombre de los elementos con el viejo|nuevo, ... pares: ", "pl": "Zmiana nazwy przedmiotów z Stare|nowe, ... par: ", "zh-cn": "重新命名项目与旧|新...对： "},
    "Scan Delay:": {                                 "en": "Delay in minutes between scans (>=5): ",          "de": "Verzögerung in Minuten zwischen Abfragen (>=5): ", "ru": "Задержку в минутах между сканированиями (>=5): ", "pt": "Atraso em minutos entre as varreduras (>=5): ",   "nl": "Vertraging in minuten tussen de scans (>=5): ",   "fr": "Délai en minutes entre les analyses (>=5): ",     "it": "Ritardo in minuti tra le scansioni (>=5): ",      "es": "Retraso en minutos entre exploraciones (>=5): ",  "pl": "Opóźnienie w minutach pomiędzy skanami (>=5): ",  "zh-cn": "延迟分钟之间的扫描(>=5): "},
    "Server:": {                                     "en": "ConnectedDrive server, in Europe 'www.bmw-connecteddrive.com': ", "de": "ConnectedDrive Server, in Europa 'www.bmw-connecteddrive.com': ", "ru": "Сервер ConnectedDrive от, в Европе 'www.bmw-connecteddrive.com': ", "pt": "ConnectedDrive servidor, na Europa \"www.bmw-connecteddrive.com': ", "nl": "ConnectedDrive server, in Europa 'www.bmw-connecteddrive.com': ", "fr": "ConnectedDrive serveur, en Europe \"www.bmw-connecteddrive.com': ", "it": "ConnectedDrive server, in Europa 'www.bmw-connecteddrive.com': ", "es": "ConnectedDrive servidor, en Europa 'www.bmw-connecteddrive.com': ", "pl": "Serwer ConnectedDrive, w Europie 'www.bmw-connecteddrive.com': ", "zh-cn": "互联驾驶服务，在欧洲'www.bmw-connecteddrive.com': "},
    "Services:": {                                   "en": "services you want to receive from ConnectedDrive: ", "de": "Services die ConnectedDrive abfragen soll: ",     "ru": "услуги вы хотите получить от ConnectedDrive от: ", "pt": "serviços que você deseja receber do ConnectedDrive: ", "nl": "diensten in die u wilt ontvangen van ConnectedDrive: ", "fr": "les services que vous souhaitez recevoir de ConnectedDrive: ", "it": "servizi che si desidera ricevere da ConnectedDrive: ", "es": "los servicios que desea recibir ConnectedDrive: ", "pl": "usługi chcesz uzyskać od ConnectedDrive od: ",    "zh-cn": "服务的你想接收从互联驾驶: "},
    "bmw adapter settings": {                        "en": "bmw adapter settings",                            "de": "BMW Adapter-Einstellungen",                       "ru": "параметры BMW адаптер ",                          "pt": "bmw configurações do adaptador",                  "nl": "bmw adapter instellingen",                        "fr": "bmw les paramètres de la carte",                  "it": "bmw impostazioni della scheda di",                "es": "bmw configuración del adaptador",                 "pl": "parametry BMW adapter ",                          "zh-cn": "bmw设置适配器"},
    "bmw settings": {                                "en": "bmw settings",                                    "de": "BMW-Einstellungen",                               "ru": "настройки БМВ ",                                  "pt": "bmw definições",                                  "nl": "bmw instellingen",                                "fr": "bmw paramètres",                                  "it": "bmw impostazioni",                                "es": "bmw configuración",                               "pl": "ustawienia BMW ",                                 "zh-cn": "bmw设置"},
    "debug": {                                       "en": "Enable debug mode!",                              "de": "Debug-Modus aktivieren!",                         "ru": "Включите режим отладки!",                         "pt": "Activar o modo de depuração!",                    "nl": "Activeer debug mode!",                            "fr": "Activez le mode de débogage!",                    "it": "Attivare la modalità di debug!",                  "es": "Habilitar el modo de depuración!",                "pl": "Włącz tryb debugowania!",                         "zh-cn": "启用调试模式！"},
    "username:": {                                   "en": "email or username used for connected drive: ",    "de": "Email oder Benutzername die für ConnectedDrive-Login verwendet wird: ", "ru": "email или имя пользователя, используемое для подключения диска: ", "pt": "email ou nome de usuário utilizado para o inversor conectado: ", "nl": "e-mail of gebruikersnaam die wordt gebruikt voor de aangesloten schijf: ", "fr": "e-mail ou nom d'utilisateur utilisé pour lecteur connecté: ", "it": "e-mail o il nome utente utilizzato per l'azionamento collegato: ", "es": "de correo electrónico o nombre de usuario utilizado para la conexión de la unidad: ", "pl": "e-mail lub nazwę użytkownika, służące do podłączenia dysku: ", "zh-cn": "电子邮件或用户名的使用对连接的驱动： "},
};